# Travis CI configuration for automated bundle generation.

dist: trusty
sudo: false
language: python
python:
    - "3.6"

cache:
    pip: true

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bundles/*
  skip_cleanup: true
  on:
    tags: true

# Note: if a packaged library is not being included in the bundle, add the folder
# name to the 'package_folder_prefix' argument list below
script: circuitpython-build-bundles --filename_prefix circuitpython-community-bundle --library_location libraries --library_depth 2 --package_folder_prefix "barbudor_ina3221, dotstar_featherwing, nonblocking_timer"
